### ISSUE TITLE
Could you provide the way to compile and install?

### ISSUE THREAD

**Issue by willzhqiang** [ValerieMayTomic/EtymOwl#1]
Hello, I am also searching for a chrome extension to search etymonline.com, so I just found your repo. But I just know how to install the extension from chrome store or ocr file, I don't know how to install from source code. Could you teach me, thanks.

**Comment by mayrohr** [comment]
Hello - sorry about the delay, I've added a compiled .crx file now. You can download just that, then drag and drop it onto the [chrome://extensions/](chrome://extensions/) page to add this extension!

**Comment by mayrohr** [comment]
Sorry, I actually realize I should upload it to the the chrome extension store, so that it will let you use it. Currently, it will disable it because it's not in the webstore.

**Comment by mayrohr** [comment]
There, I've published it on the Chrome webstore now. It might take a few minutes to update, but you should be able to install it directly [here](https://chrome.google.com/webstore/detail/etymowl/oepibkigmjnfkccnanahnpijjkjafjdk)!

**Comment by willzhqiang** [comment]
Hello, I just installed and tested it, it works. Thanks very much!
